### ISSUE TITLE
hidden character crash

### ISSUE THREAD

**Issue by mikegiddens** [Vizzuality/cartodb-gmapsv3#27]
cartodb-gmapsv3.js
L 47/48 has a funky character after || and is crashing the js.  If you remove it all works.  You can see the char if you browse the code.

**Comment by xavijam** [comment]
Thanks Mike! Should be fixed now :).
https://github.com/Vizzuality/cartodb-gmapsv3/commit/33aca4fbafc03423cb9473a4b29cbb5aacda7bea
