### ISSUE TITLE
Click on drawing manager icons is interpreted as a click on cartodb layer

### ISSUE THREAD

**Issue by sidkshatriya** [Vizzuality/cartodb-gmapsv3#29]
I am using UTFgrid based interactivity on my map. It works fine.

However, I am using the Google drawing manager (see https://developers.google.com/maps/documentation/javascript/overlays#drawing_tools )

See here for an example https://google-developers.appspot.com/maps/documentation/javascript/examples/drawing-tools

The problem is whenever I click on any of the any of the icons (e.g. the hand), the carto db layer thinks I am clicking on the feature.

**Comment by xavijam** [comment]
You need to stop the propagation of the click event. No idea if GMaps v3 allows to add a listener to those buttons.

**Comment by sidkshatriya** [comment]
Actually, this happens even when I click on things like Map type selection (Map, Satellite) or the direction circle. Its not limited to drawing manager.

**Comment by xavijam** [comment]
I'll take a look if it is possible to manage this issue.

**Comment by sidkshatriya** [comment]
Any luck here ? Thanks!

**Comment by sidkshatriya** [comment]
Here is a workaround for this (assumes you have jQuery):

``` php
      featureClick: function(event, latlng, pos, data) {
        // IMPORTANT. Some clicks are to the drawing manager for instance
        // we want to ignore those. This fixes this quirk.
        if($(event.target).parents().hasClass('gmnoprint')) {
          return;
        }

        // normal featureClick code
        ...
        ...
      }
```

**Comment by xavijam** [comment]
Great patch!

Thanks for sharing with us!
