### ISSUE TITLE
Interactivity layer steals infowindow close "click" event

### ISSUE THREAD

**Issue by tokumine** [Vizzuality/cartodb-gmapsv3#3]
**reproduce**
1. Make a geometry that is very large
2. Make sure Infowindow appears totally surrounded by geometry
3. try to close infowindow

**expected**

close the infowindow

**observed**

doesn't close.

Thanks to josh on the forums: http://support.cartodb.com/discussions/problems/36-infowindow-in-gmaps-cartodb-library

**Comment by xavijam** [comment]
http://dl.dropbox.com/u/931536/Screen%20Recording%204.mov
