### ISSUE TITLE
Wax multiply replace of x, y, z

### ISSUE THREAD

**Issue by mikegiddens** [Vizzuality/cartodb-gmapsv3#32]
in your last few lines of wax you need to change to 
.replace(/{z}/g,c).replace(/{x}/g,a).replace(/{y}/g,d)};

this will allow all cases of {x} in your path to be swapped.  There are cases were this is useful and right now it only replaces the first one.

**Comment by rpsirois** [comment]
Update:

This hack seems to be broken with Wax 6.2.0-touched. It was working with 6.0.4.

**Comment by rpsirois** [comment]
This issue can be closed. I completely forgot I changed the last few lines in the wax file (replacing the quotes with regex):

Before:

```
return this.options.tiles
    [parseInt(x + y, 10) %
        this.options.tiles.length]
            .replace('{z}', z)
            .replace('{x}', x)
            .replace('{y}', y);
```

After:

```
return this.options.tiles
    [parseInt(x + y, 10) %
        this.options.tiles.length]
            .replace(/{z}/g, z)
            .replace(/{x}/g, x)
            .replace(/{y}/g, y);
```

Thanks!

**Comment by xavijam** [comment]
Hi both!

Sorry to answer to this issue so late, but in the recent versions it is fixed, isn't it?

Cheers
