### ISSUE TITLE
Why no links to individual examples?

### ISSUE THREAD

**Issue by andrewxhill** [Vizzuality/cartodb-gmapsv3#34]
From the GH Pages site,

http://vizzuality.github.com/cartodb-gmapsv3/

There don't seem to be nice links to each of the individual examples. Such great resources, might be handy.

(same in leaflet lib)

**Comment by saleiva** [comment]
+1 :)

**Comment by xavijam** [comment]
Done, and in leaflet library as well. :)

(Waiting for github to make it public with gh-pages :S)
