### ISSUE TITLE
wax binding listener multiple firing

### ISSUE THREAD

**Issue by mikegiddens** [Vizzuality/cartodb-gmapsv3#35]
The binding listner is still happening after your bug fix so I think there is still something missing with the code.

Simple test I do in FF is to go to your example page http://vizzuality.github.com/cartodb-gmapsv3/ and right now the var is making them private which global would be better for testing purposes but I just copy you code in firebug then I can run commands like:

cartodb2_gmapsv3.setQuery("SELECT cartodb_id,the_geom_webmercator,magnitude FROM {{table_name}} WHERE magnitude > 1");

cartodb2_gmapsv3.setQuery("SELECT cartodb_id,the_geom_webmercator,magnitude FROM {{table_name}} WHERE magnitude > 1");

cartodb2_gmapsv3.setQuery("SELECT cartodb_id,the_geom_webmercator,magnitude FROM {{table_name}} WHERE magnitude > 1");

cartodb2_gmapsv3.setQuery("SELECT cartodb_id,the_geom_webmercator,magnitude FROM {{table_name}} WHERE magnitude > 2");

cartodb2_gmapsv3.setQuery("SELECT cartodb_id,the_geom_webmercator,magnitude FROM {{table_name}} WHERE magnitude > 1");

cartodb2_gmapsv3.setQuery("SELECT cartodb_id,the_geom_webmercator,magnitude FROM {{table_name}} WHERE magnitude > 3");

cartodb2_gmapsv3.setQuery("SELECT cartodb_id,the_geom_webmercator,magnitude FROM {{table_name}} WHERE magnitude > 1");

cartodb2_gmapsv3.setQuery("SELECT cartodb_id,the_geom_webmercator,magnitude FROM {{table_name}} WHERE magnitude > 4");

**Comment by xavijam** [comment]
Hi Mike!

Hope the bug is now fixed. Could you take a look? Use the 'wax.g.min.js' file in the library please.

Cheers!
