### ISSUE TITLE
Hide and SetInteraction problems with Wax grids

### ISSUE THREAD

**Issue by mikegiddens** [Vizzuality/cartodb-gmapsv3#40]
if you call layer.hide() for layer.setInteraction(false) the wax listeners are not getting turned off and causing featureClick to behave to layers that should not be active.  Just call either one of these functions and look at your network.

also something that would be helpful is on the http://vizzuality.github.com/cartodb-gmapsv3/ example if you could take out the var map  and var layers so that we can test things with the libarary with your example directly in a dev console.  Right now the var is keeping them private.

**Comment by xavijam** [comment]
Sorry Mike, but this is not happening to me, when .hide or .setInteraction are applied the interaction is removed and any funcion is not fired. I've updated the library, could you take another look? Thanks.

**Comment by xavijam** [comment]
And one more thing, if you want to try the library funcionalities you can do it in custom-infowindow.html. But in any case, I encourage you to download the whole library with the examples and try them in local.
Cheers!
